# Site settings
title: LukeGeeson
email: mail@lukegeeson.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: lukegeeson
github_username:  lukeg101

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  talks:
    output: true
    permalink: /talks/:path/
  blog:
    output: true
    permanlink: /blog/:path/
