# Site settings
title: LukeGeeson
email: mail@lukegeeson.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lukegeeson.com" # the base hostname & protocol for your site
enforce_ssl: lukegeeson.com
twitter_username: lukegeeson
github_username:  lukeg101

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  talks:
    output: true
    permalink: /talks/:path/
  blog:
    output: true
    permalink: /blog/:path/

plugins: 
  - jekyll
  - github-pages
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  - links:
    - https://www.twitter.com/lukegeeson
    - https://uk.linkedin.com/in/lukegeesonhttps://uk.linkedin.com/in/lukegeeson
    - https://github.com/lukeg101
